name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      - uses: ACyphus/random-word-slugs-action@v1.0.0
        with:
          # The number of words to generate
          number-of-words: 1 # optional, default is 3
    
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USER }}  
          password: ${{ secrets.PASSWD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            sebashub/mercado_project:${{ steps.generate-words.outputs.words-kebab }}
            sebashub/mercado_project:latest
            
